### ISSUE TITLE
Missing required param groupId after logout

### ISSUE THREAD

**Issue by jvanveen** [garage44/pyrite#73]
```
vue-router.esm-bundler.js:1006 Uncaught Error: Missing required param "groupId"
    at Object.stringify (vue-router.esm-bundler.js:1006:35)
    at Object.resolve (vue-router.esm-bundler.js:1424:28)
    at resolve (vue-router.esm-bundler.js:2908:38)
    at pushWithRedirect (vue-router.esm-bundler.js:2996:51)
    at Object.push (vue-router.esm-bundler.js:2962:16)
    at SfuModel.onClose (sfu.js?t=1642763887148:300:20)
    at WebSocket.socket.onclose (protocol.js:291:28)
```

Also check whether the current routings between group and login are logical.

**Comment by jvanveen** [comment]
This was caused by switching between admin and conference mode, where the group was still connected. It seems to me unwanted to keep a group open, while fiddling around in the admin view. The link to admin is now inactive while the (admin) user is still connected to a group. Also, the computed property for the link has been fixed.
